# Imports.
# Local imports.
from biome import Biome, Entry
from enums import BodyPart, NpcTypes, EntryType
from item import Item
from npc import Npc

# Command line settings.
WIDTH = 92
HEIGHT = 32

# Patron.
PATRON = [" / /\  ", "/ /\ \ ", "\ \/ / ", " \/ /  ", " / /\  ", "/ /\ \ ", "\ \/ / ", " \/ /  "]

# Directions.
DIRECTIONS = {0: "1 - NORTH", 1: "2 - EAST", 2: "3 - SOUTH", 3: "4 - WEST"}

# Colors.
WHITE = (255, 255, 255, 255)
PINK = (255, 105, 180, 255)

# Bioms of map.
BIOMES = {
    "canyon": Biome(
        color=(54, 54, 54, 255),
        description="Shadowy canyon inhabited by fearsome creatures, dark depths, echoing roars, and lurking horrors",
        fight=True,
        mobs=["basilisk", "giant blind spider", "orc", "spectrum"],
        mobs_chances=[30, 50, 10, 30],
        name="CANYON",
        req=["torch"],
        pace=12,
        status=[0]),
    "cave": Biome(
        color=(1, 1, 1, 255),
        description="...",
        fight=True,
        mobs=["goblin", "orcs"],
        mobs_chances=[80, 50],
        name="CAVE",
        req=["torch"],
        status=[0]),
    "coast": Biome(
        color=(239, 228, 176, 255),
        description="Seaside with swaying palm trees, echoing waves, and vibrant life.",
        fight=True,
        mobs=["litle slime", "slime"],
        mobs_chances=[5, 30],
        name="COAST",
        req=[],
        status=[0, 1]),
    "dark forest": Biome(
        color=(22, 118, 51, 255),
        description="Shadowy forest of peril, twisted trees loom overhead, their gnarled branches casting eerie "
                    "shadows. ",
        fight=True,
        mobs=["spectral foxshade", "giant spider"],
        mobs_chances=[1, 30],
        name="DARK FOREST",
        req=[],
        status=[0]),
    "death valley": Biome(
        color=(148, 148, 148, 255),
        description="Dreadful dead valley, a chilling abyss where every step deepens the terror within. The air grows "
                    "heavy, and eerie whispers intensify, inducing an unsettling unease as you delve further.",
        fight=True,
        mobs=[],
        mobs_chances=[],
        name="DEATH VALLEY",
        req=[],
        status=[0]),
    "fields": Biome(
        color=(115, 231, 29, 255),
        description="Verdant fields, rolling emerald expanses dotted with wildflowers, where gentle breezes carry the "
                    "sweet scent of blooming herbs and distant melodies from hidden creatures in the tall grass.",
        fight=True,
        mobs=["dryad", "slime"],
        mobs_chances=[15, 30],
        name="FIELDS",
        req=[],
        status=[0]),
    "forest": Biome(
        color=(34, 177, 76, 255),
        description="Thick trees, vibrant flora, wildlife, hidden trails, and lurking danger in this treacherous "
                    "forest realm.",
        fight=True,
        mobs=["bandit", "spectral foxshade"],
        mobs_chances=[20, 1],
        name="FOREST",
        req=[],
        status=[0]),
    "frostvale": Biome(
        color=(120, 186, 252, 255),
        description="A pristine, snow-covered expanse where frost-kissed silence reigns. Glistening ice formations "
                    "adorn the landscape, creating an ethereal and serene winter tableau in nature's icy embrace.",
        fight=False,
        mobs=[],
        mobs_chances=[],
        name="FROSTVALE",
        req=[],
        status=[0]),
    "gates": Biome(
        color=(200, 191, 231, 255),
        description="Nothing important.",
        fight=False,
        mobs=[],
        mobs_chances=[],
        name="GATES",
        req=[],
        status=[0]),
    "highlands": Biome(
        color=(195, 195, 195, 255),
        description="Rugged terrain, sinister caves, and sneaky goblin tribes dominate these perilous elevated lands.",
        fight=True,
        mobs=["goblin"],
        mobs_chances=[40],
        name="HIGHLANDS",
        req=[],
        status=[0]),
    "hills": Biome(
        color=(78, 185, 32, 255),
        description="Undulating landscapes concealing lurking dangers. Treacherous creatures, hidden in the shadows, "
                    "make these hills a realm of risk for those who dare to traverse their slopes.",
        fight=True,
        mobs=["climbing goblin", "troll", "goblin war chief"],
        mobs_chances=[30, 30, 5],
        name="HILLS",
        req=[],
        status=[0]),
    "hut": Biome(
        color=(185, 122, 87, 255),
        description="Nothing important.",
        entries={"hut": Biome(description="Island hut, a cozy retreat adorned with a bed, a table, two "
                                          "chairs, and a window, invites serenity amid nature's whispers.",
                              items=["bed"])},
        fight=False,
        items=[],
        mobs=[],
        mobs_chances=[],
        name="HUT",
        req=[],
        status=[0]),
    "island": Biome(
        color=(201, 237, 92, 255),
        description="Island rainforest, dense foliage, vibrant biodiversity, and cascading waterfalls characterize "
                    "this tropical haven of life and greenery.",
        fight=True,
        mobs=["litle slime"],
        mobs_chances=[30],
        name="ISLAND",
        req=[],
        status=[0]),
    "mountains": Biome(
        color=(127, 127, 127, 255),
        description="Nothing important.",
        fight=False,
        mobs=[],
        mobs_chances=[],
        name="MOUNTAINS",
        req=["climbing tools"],
        status=[0]),
    "plains": Biome(
        color=(181, 230, 29, 255),
        description="Gentle terrain, waving grasslands, and minimal elevation define this vast, open expanse of natural"
                    " simplicity and beauty.",
        fight=True,
        mobs=["giant slime", "goblin", "slime"],
        mobs_chances=[20, 30, 30],
        name="PLAINS",
        req=[],
        status=[0]),
    "plateau": Biome(
        color=(181, 230, 29, 255),
        description="Elevated plateau, expansive views, flat summits, and resilient flora characterize this "
                    "high-altitude, majestic landscape.",
        fight=True,
        mobs=["slime"],
        mobs_chances=[30],
        name="PLATEAU",
        req=[],
        status=[0]),
    "red": Biome(
        color=(255, 0, 0, 255),
        description="Nothing important.",
        fight=True,
        mobs=[],
        mobs_chances=[],
        name="RED",
        req=[],
        status=[0]),
    "river": Biome(
        color=(0, 162, 232, 255),
        description="Nothing important.",
        fight=True,
        mobs=[],
        mobs_chances=[],
        name="RIVER",
        req=[],
        status=[1]),
    "rocks": Biome(
        color=(85, 80, 85, 255),
        description="Nothing important.",
        fight=False,
        mobs=[],
        mobs_chances=[],
        name="ROCKS",
        req=["wings"],
        status=[0]),
    "sea": Biome(
        color=(63, 72, 204, 255),
        description="Nothing important.",
        fight=False,
        mobs=[],
        mobs_chances=[],
        name="SEA",
        req=[],
        status=[1]),
    "snow": Biome(
        color=(250, 250, 250, 255),
        description="Nothing important.",
        fight=True,
        mobs=[],
        mobs_chances=[],
        name="SNOW",
        req=["snow clothing"],
        status=[0]),
    "town": Biome(
        color=(170, 105, 70, 255),
        description="Nothing important.",
        fight=False,
        mobs=[],
        mobs_chances=[],
        name="TOWN",
        req=[],
        status=[0]),
    "valley": Biome(
        color=(167, 167, 167, 255),
        description="Desolate, silent valley, cracked earth stretches between imposing cliffs, where an eerie stillness"
                    " envelops the barren landscape, untouched by the whispers of wind or the rustle of life.",
        fight=False,
        mobs=[],
        mobs_chances=[],
        name="VALLEY",
        req=[],
        status=[0]),
    "water": Biome(
        color=(128, 255, 255, 255),
        description="Quiet water.",
        fight=False,
        mobs=[],
        mobs_chances=[],
        name="WATER",
        req=[],
        status=[1])
}

ENTRIES = {
    "cave_13_0": Entry(
        description="Echoing cave, shadows stretch across damp walls, while unsettling sounds resonate from unseen"
                    " depths, hinting at hidden creatures lurking within the dark.",
        name="CAVE ENTRANCE",
        hide={"visibility": False, "finding_chance": 0.80},
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["goblin"],
        mobs_chances=[40],
        req=["torch"]),

    "sub_cave_1_0": Entry(
        description="Cave pit, jagged walls descend into darkness, littered with bones and crude markings. The air is"
                    " thick with the stench of decay and faint goblin whispers.",
        name="CAVE PIT",
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["goblin"],
        mobs_chances=[40]),

    "sub_cave_1_1": Entry(
        description="Goblin lookout hole, roughly dug with narrow slits for spying, scattered with makeshift weapons."
                    " Flickering torchlight reveals grimy walls and vigilant goblin eyes peering into the shadows.",
        name="GOBLIN LOOKOUT HOLE",
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["watchful goblin", "goblin war"],
        mobs_chances=[90, 30]),

    "sub_cave_1_2": Entry(
        description="Crude racks hold jagged weapons, rusted blades, and splintered shields. The walls bear scratch "
                    "marks, and a foul smell lingers amid the chaotic stash.",
        name="GOBLIN'S ARMORY CAVE",
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["goblin", "goblin war"],
        mobs_chances=[30, 60]),

    "sub_cave_2_0": Entry(
        description="Basin, murky, foul-smelling pool at the pit's depths, filled with discarded scraps, broken bones,"
                    " and refuse. A grimy layer coats the stagnant surface, emitting a nauseating stench.",
        name="CAVE BASIN",
        entry_type=EntryType.CAVE,
        fight=False),

    "sub_cave_2_1": Entry(
        description="Goblin chief's cave, dark and cluttered, adorned with stolen trinkets and crude trophies. A "
                    "makeshift throne sits in the center, surrounded by flickering torches.",
        name="CHIEF'S CAVE",
        entry_type=EntryType.CAVE,
        fight=True, ),

    "sub_cave_2_2": Entry(
        description="Goblin chief's bedroom, dimly lit by flickering torches, the room is strewn with riches and "
                    "treasures. Shackled prisoners lie in the shadows, while the chief’s bed, made of rough furs, "
                    "dominates the chaotic space.",
        name="GOBLIN CHIEF'S BEDROOM",
        entry_type=EntryType.CAVE,
        fight=False),

    "sub_cave_2_3": Entry(
        description="Cave passage, narrow and winding, with jagged walls and low ceilings. The air is damp, filled "
                    "with the faint sound of scurrying feet and the occasional echo of distant growls.",
        name="CAVE PASSAGE ENTRANCE",
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["goblin", "goblin war"],
        mobs_chances=[60, 20]),

    "sub_cave_2_4": Entry(
        description="Goblin cave cage chamber, rows of rusted iron cages line the damp stone walls, holding captives "
                    "in grim silence. The air is thick with tension, and the faint clinking of chains echoes "
                    "throughout.",
        name="CAGE CHAMBER",
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["goblin", "goblin war"],
        mobs_chances=[60, 20]),

    "sub_cave_3_0": Entry(
        description="Towering stalactites hang from the ceiling, casting eerie shadows in the dim light. The damp air"
                    " drips steadily, creating a haunting, rhythmic echo throughout the chamber.",
        name="CAVE GALLERY",
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["goblin", "goblin war"],
        mobs_chances=[60, 20]),

    "sub_cave_3_1": Entry(
        description="Cave passage, narrow and winding, with jagged walls and low ceilings. The air is damp, filled "
                    "with the faint sound of scurrying feet and the occasional echo of distant growls.",
        name="CAVE PASSAGE EXIT",
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["goblin", "goblin war"],
        mobs_chances=[50, 50]),

    "sub_cave_3_2": Entry(
        description="Crude stone tables scattered with scraps of half-eaten food and cracked bones. The air is "
                    "thick with the smell of rancid meat, and discarded remnants litter the grimy floor.",
        name="GOBLIN DINING GALLERY",
        entry_type=EntryType.CAVE,
        fight=True,
        mobs=["goblin", "goblin war"],
        mobs_chances=[70, 70]),

    "sub_cave_4_0": Entry(
        description="Unused goblin cave chimney. A narrow, soot-stained shaft reaching upward, clogged with debris "
                    "and cobwebs. Cold drafts whistle through, hinting at an abandoned escape route to the surface.",
        name="CHIMNEY CAVE",
        entry_type=EntryType.CAVE,
        hide={"visibility": False, "finding_chance": 0.9}),

    "hut_0_0": Entry(
        description="Island hut, a cozy retreat adorned with a bed, a table, two chairs, and a window, "
                    "invites serenity amid nature's whispers.",
        items=["bed", "short_sword", "bread", "apple"]),

    "hut_1_23": Entry(
        description="Interior of isolated refuge, dimly lit, flickering candles cast dancing shadows "
                    "on weathered walls. Tattered maps and makeshift barricades hint at cautious attempts"
                    " to secure the uncertain safety within.",
        items=["bed"]),

    "mirabelles_inn": Entry(
        description="Warm hearth, wooden beams, and cozy furnishings create a welcoming "
                    "atmosphere. Aromas of home-cooked meals linger, inviting weary travelers to "
                    "find respite.",
        name="MIRABELLE'S INN",
        npc=["innkeeper mirabelle", "villager doran"]),

    "mirabelles_main_room": Entry(
        description="In the main chamber of the inn, a comfortable bed awaits amidst the charming ambiance of "
                    "a warm hearth, rustic wooden beams, and snug furnishings.",
        items=["bed"],
        name="MIRABELLE'S INN MAIN ROOM",
        req=["mirabelles_main_room_key"]),

    "mirabelles_small_room": Entry(
        description="In the main chamber of the inn, a comfortable bed awaits amidst the charming ambiance of "
                    "a warm hearth, rustic wooden beams, and snug furnishings.",
        items=["bed"],
        name="MIRABELLE'S INN SMALL ROOM",
        req=["mirabelles_small_room_key"])
}

ITEMS = {
    # Equippable items.
    "axe": Item(name="Axe",
                description="A rugged Axe: perfect for chopping wood or cleaving enemies with powerful, heavy strikes.",
                attack=4,
                defense=0,
                precision=0,
                evasion=0,
                body_part=BodyPart.RIGHT_HAND,
                pickable=True,
                consumable=False,
                equippable=True,
                expiration=None,
                buy_price=200,
                sell_price=150),
    "bludgeon": Item(name="Axe",
                     description="Hefty Bludgeon blunt and brutal, ideal for stunning foes with a single, "
                                 "powerful blow.",
                     attack=2,
                     defense=0,
                     precision=0,
                     evasion=0,
                     body_part=BodyPart.RIGHT_HAND,
                     pickable=True,
                     consumable=False,
                     equippable=True,
                     expiration=None,
                     buy_price=200,
                     sell_price=40),
    "chainmail_armor": Item(name="Chainmail Armor",
                            description=("Sturdy armor made of interlocked rings. Offers great protection for the "
                                         "chest."),
                            attack=0,
                            defense=3,
                            precision=0,
                            evasion=0,
                            body_part=BodyPart.CHEST,
                            pickable=True,
                            consumable=False,
                            equippable=True,
                            expiration=None,
                            buy_price=500,
                            sell_price=150),
    "hardened_leather_armor": Item(name="Hardened Leather Armor",
                                   description=("Thick, reinforced leather armor. Flexible and offers decent "
                                                "protection."),
                                   attack=0,
                                   defense=2,
                                   precision=0,
                                   evasion=0,
                                   body_part=BodyPart.CHEST,
                                   pickable=True,
                                   consumable=False,
                                   equippable=True,
                                   expiration=None,
                                   buy_price=300,
                                   sell_price=60),
    "harpoon": Item(name="Harpoon",
                    description="A sharp harpoon for striking enemies from a distance. Balanced and quick.",
                    attack=2,
                    defense=0,
                    precision=0,
                    evasion=0.1,
                    body_part=BodyPart.RIGHT_HAND,
                    pickable=True,
                    consumable=False,
                    equippable=True,
                    expiration=None,
                    buy_price=150,
                    sell_price=40),
    "iron_shield": Item(name="Iron Shield",
                        description="Solid iron shield. Blocks incoming attacks with ease.",
                        attack=0,
                        defense=3,
                        precision=0,
                        evasion=0,
                        body_part=BodyPart.LEFT_HAND,
                        pickable=True,
                        consumable=False,
                        equippable=True,
                        expiration=None,
                        buy_price=400,
                        sell_price=75),
    "large_bow": Item(name="Large Bow",
                      description="A hefty bow designed for long-range attacks. Great precision and speed.",
                      attack=2,
                      defense=0,
                      precision=0.15,
                      evasion=0.30,
                      body_part=BodyPart.RIGHT_HAND,
                      pickable=True,
                      consumable=False,
                      equippable=True,
                      expiration=None,
                      buy_price=350,
                      sell_price=110),
    "leather_armor": Item(name="Leather Armor",
                          description="Basic leather armor. Provides light protection to the chest.",
                          attack=0,
                          defense=1,
                          precision=0,
                          evasion=0,
                          body_part=BodyPart.CHEST,
                          pickable=True,
                          consumable=False,
                          equippable=True,
                          expiration=None,
                          buy_price=200,
                          sell_price=35),
    "leather_boots": Item(name="Leather Boots",
                          description="Sturdy boots made of leather. Offers some defense for your legs.",
                          attack=0,
                          defense=1,
                          precision=0,
                          evasion=0,
                          body_part=BodyPart.LEGS,
                          pickable=True,
                          consumable=False,
                          equippable=True,
                          expiration=None,
                          buy_price=150,
                          sell_price=25),
    "longsword": Item(name="Longsword",
                      description="A finely crafted longsword. Perfect for dealing heavy, precise strikes.",
                      attack=4,
                      defense=0,
                      precision=0.05,
                      evasion=0,
                      body_part=BodyPart.RIGHT_HAND,
                      pickable=True,
                      consumable=False,
                      equippable=True,
                      expiration=None,
                      buy_price=500,
                      sell_price=175),
    "mesh_boots": Item(name="Mesh Boots",
                       description="Flexible boots with added defense. Protects legs while maintaining mobility.",
                       attack=0,
                       defense=2,
                       precision=0,
                       evasion=0,
                       body_part=BodyPart.LEGS,
                       pickable=True,
                       consumable=False,
                       equippable=True,
                       expiration=None,
                       buy_price=250,
                       sell_price=50),
    "plate_armor": Item(name="Plate Armor",
                        description="Heavy plate armor that offers superior protection to the chest.",
                        attack=0,
                        defense=4,
                        precision=0,
                        evasion=0,
                        body_part=BodyPart.CHEST,
                        pickable=True,
                        consumable=False,
                        equippable=True,
                        expiration=None,
                        buy_price=700,
                        sell_price=200),
    "short_sword": Item(name="Short Sword",
                        description=("A trusty Short Sword, swift and precise, ideal for close-quarter battles against "
                                     "foes in the wild."),
                        attack=1,
                        defense=0,
                        precision=0,
                        evasion=0,
                        body_part=BodyPart.RIGHT_HAND,
                        pickable=True,
                        consumable=False,
                        equippable=True,
                        expiration=None,
                        buy_price=150,
                        sell_price=50),
    "spear": Item(name="Spear",
                  description="A long spear for thrusting attacks. Great reach and balance.",
                  attack=3,
                  defense=0,
                  precision=0.05,
                  evasion=0.15,
                  body_part=BodyPart.RIGHT_HAND,
                  pickable=True,
                  consumable=False,
                  equippable=True,
                  expiration=None,
                  buy_price=300,
                  sell_price=125),
    "spike_shield": Item(name="Spike Shield",
                         description="A sturdy shield with deadly spikes. Can block and deal damage.",
                         attack=1,
                         defense=3,
                         precision=0,
                         evasion=0,
                         body_part=BodyPart.LEFT_HAND,
                         pickable=True,
                         consumable=False,
                         equippable=True,
                         expiration=None,
                         buy_price=500,
                         sell_price=150),
    "sword": Item(name="Sword",
                  description="A balanced sword. Reliable for close combat with decent attack power.",
                  attack=3,
                  defense=0,
                  precision=0.05,
                  evasion=0,
                  body_part=BodyPart.RIGHT_HAND,
                  pickable=True,
                  consumable=False,
                  equippable=True,
                  expiration=None,
                  buy_price=400,
                  sell_price=150),
    "tower_shield": Item(name="Tower Shield",
                         description="A massive shield offering unparalleled defense. Best for tanking heavy attacks.",
                         attack=0,
                         defense=4,
                         precision=0,
                         evasion=0,
                         body_part=BodyPart.LEFT_HAND,
                         pickable=True,
                         consumable=False,
                         equippable=True,
                         expiration=None,
                         buy_price=600,
                         sell_price=150),
    "wood_shield": Item(name="Wood Shield",
                        description="A simple wooden shield. Provides basic defense.",
                        attack=0,
                        defense=1,
                        precision=0,
                        evasion=0,
                        body_part=BodyPart.LEFT_HAND,
                        pickable=True,
                        consumable=False,
                        equippable=True,
                        expiration=None,
                        buy_price=100,
                        sell_price=20),

    # Consumable items.
    "apple": Item(name="Apple",
                  description="A fresh, red apple. Satisfies hunger but offers no special effects.",
                  attack=0,
                  defense=0,
                  precision=0,
                  evasion=0,
                  pickable=True,
                  consumable=True,
                  equippable=False,
                  expiration=None,
                  buy_price=1,
                  sell_price=1),
    "antidote": Item(name="Antidote",
                     description="A small vial that cures poison. Essential for survival in venomous areas.",
                     attack=0,
                     defense=0,
                     precision=0,
                     evasion=0,
                     pickable=True,
                     consumable=True,
                     equippable=False,
                     expiration=None,
                     buy_price=5,
                     sell_price=3),
    "basilisk_fangs": Item(name="Basilisk Fangs",
                           description="Deadly fangs of a basilisk. Handle with care, might still be venomous.",
                           attack=0,
                           defense=0,
                           precision=0,
                           evasion=0,
                           pickable=True,
                           consumable=False,
                           equippable=False,
                           expiration=None,
                           buy_price=15,
                           sell_price=15),
    "bier": Item(name="Bier",
                 description="A simple bier. Helps recover energy after a long day's journey.",
                 attack=0,
                 defense=0,
                 precision=0,
                 evasion=0,
                 pickable=True,
                 consumable=True,
                 equippable=False,
                 expiration=None,
                 buy_price=1,
                 sell_price=1),
    "bread": Item(name="Bread",
                  description="A crusty loaf of bread, filling and freshly baked for hungry travelers.",
                  attack=0,
                  defense=0,
                  precision=0,
                  evasion=0,
                  pickable=True,
                  consumable=True,
                  equippable=False,
                  expiration=None,
                  buy_price=1,
                  sell_price=1),
    "cheese": Item(name="Cheese",
                   description="A wedge of cheese. Restores energy but offers no additional effects.",
                   attack=0,
                   defense=0,
                   precision=0,
                   evasion=0,
                   pickable=True,
                   consumable=True,
                   equippable=False,
                   expiration=None,
                   buy_price=2,
                   sell_price=2),
    "fishing_pole": Item(name="Fishing Pole",
                         description="A sturdy pole for fishing. A useful tool for catching food.",
                         attack=0,
                         defense=0,
                         precision=0,
                         evasion=0,
                         pickable=True,
                         consumable=False,
                         equippable=False,
                         expiration=None,
                         buy_price=25,
                         sell_price=25),
    "giant_red_potion": Item(name="Giant Red Potion",
                             description="A large red potion that restores a significant amount of health.",
                             attack=0,
                             defense=0,
                             precision=0,
                             evasion=0,
                             pickable=True,
                             consumable=True,
                             equippable=False,
                             expiration=None,
                             buy_price=10,
                             sell_price=10),
    "giant_silk": Item(name="Giant Silk",
                       description="Silk from a giant spider. Valuable for crafting or trading.",
                       attack=0,
                       defense=0,
                       precision=0,
                       evasion=0,
                       pickable=True,
                       consumable=False,
                       equippable=False,
                       expiration=None,
                       buy_price=30,
                       sell_price=30),
    "litle_red_potion": Item(name="Little Red Potion",
                             description="A small potion that restores a minor amount of health.",
                             attack=0,
                             defense=0,
                             precision=0,
                             evasion=0,
                             pickable=True,
                             consumable=True,
                             equippable=False,
                             expiration=None,
                             buy_price=2,
                             sell_price=2),
    "red_potion": Item(name="Red Potion",
                       description="A standard red potion to restore health during battle.",
                       attack=0,
                       defense=0,
                       precision=0,
                       evasion=0,
                       pickable=True,
                       consumable=True,
                       equippable=False,
                       expiration=None,
                       buy_price=5,
                       sell_price=5),
    "slime_balls": Item(name="Slime Balls",
                        description="Gooey remnants of a defeated slime. Maybe useful, but hard to tell.",
                        attack=0,
                        defense=0,
                        precision=0,
                        evasion=0,
                        pickable=True,
                        consumable=False,
                        equippable=False,
                        expiration=None,
                        buy_price=1,
                        sell_price=1),
    "soup": Item(name="Soup",
                 description="A warm bowl of hearty soup, perfect for cold, weary adventurers.",
                 attack=0,
                 defense=0,
                 precision=0,
                 evasion=0,
                 pickable=True,
                 consumable=False,
                 equippable=False,
                 expiration=None,
                 buy_price=1,
                 sell_price=1),
    "telescope": Item(name="Telescope",
                      description="A long-range viewing device.",
                      attack=0,
                      defense=0,
                      precision=0,
                      evasion=0,
                      pickable=True,
                      consumable=False,
                      equippable=False,
                      expiration=None,
                      buy_price=125,
                      sell_price=125),
    "torch": Item(name="Torch",
                  description="A burning torch to light the way. Useful in dark places.",
                  attack=0,
                  defense=0,
                  precision=0,
                  evasion=0,
                  pickable=True,
                  consumable=True,
                  equippable=False,
                  expiration=None,
                  buy_price=10,
                  sell_price=10),
    "water": Item(name="Water",
                  description="A bottle of clean water. Refreshing and essential for survival.",
                  attack=0,
                  defense=0,
                  precision=0,
                  evasion=0,
                  pickable=True,
                  consumable=True,
                  equippable=False,
                  expiration=None,
                  buy_price=1,
                  sell_price=1),

    # Places items.
    "bed": Item(name="Bed",
                description="Simple yet soft, promising warmth and restful sleep in humble surroundings",
                attack=0,
                defense=0,
                precision=0,
                evasion=0,
                pickable=False,
                consumable=False,
                equippable=False,
                expiration=None,
                buy_price=300,
                sell_price=150),
    "boat": Item(name="Boat",
                 description="A sturdy sooden ship crafted to brave the seas, steady against waves and fierce winds.",
                 attack=0,
                 defense=0,
                 precision=0,
                 evasion=0,
                 pickable=False,
                 consumable=False,
                 equippable=False,
                 expiration=None,
                 buy_price=1000,
                 sell_price=700),
    "origame_flowers": Item(name="Origame Flowers",
                            description="Paper flowers, seem to have something inside the stem, but you can't get it "
                                        "out with your fingers, you need a long stick."),

    # Innkeeper room keys.
    "mirabelles_small_room_key": Item(name="Mirabelle's Small Room Key",
                                      description="Small room key, worn and simple, granting access to a modest inn"
                                                  " chamber.",
                                      expiration=30,
                                      buy_price=3),

    "mirabelles_main_room_key": Item(name="Mirabelle's Small Room Key",
                                     description="Small room key, worn and simple, granting access to a modest inn"
                                                 " chamber.",
                                     expiration=30,
                                     buy_price=5),

    # Others.
    "quit": Item(name="Quit",
                 description="This item ends the game session when used."),
}

# MOBS.
MOBS = {
    "bandit": {
        "name": "Bandit",
        "hp": 30,
        "hpmax": 30,
        "atk": 3,
        "def": 2,
        "eva": 0.4,
        "pre": 0.8,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 40,
        "items": {"gold": 15, "red_potion": 1, "none": None},
        "dc_items": [0.5, 0.7, 1],
        "exp": 4,
    },
    "basilisk": {
        "name": "Basilisk",
        "hp": 80,
        "hpmax": 80,
        "atk": 12,
        "def": 8,
        "eva": 0.6,
        "pre": 0.7,
        "c_coef": 1.7,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 20,
        "items": {"basilisk_fangs": 2, "none": None},
        "dc_items": [0.7, 1],
        "exp": 10
    },
    "climbing goblin": {
        "name": "Climbing Goblin",
        "hp": 35,
        "hpmax": 35,
        "atk": 7,
        "def": 4,
        "eva": 0.3,
        "pre": 0.8,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 40,
        "items": {"gold": 20, "red_potion": 1, "wood_shield": 1, "none": None},
        "dc_items": [0.5, 0.6, 0.65, 1],
        "exp": 6
    },
    "dragon": {
        "name": "Dragon FireFrost",
        "hp": 10,
        "hpmax": 10,
        "atk": 15,
        "def": 10,
        "eva": 0.5,
        "pre": 0.9,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 0,
        "items": {"none": None},
        "dc_items": [1],
        "exp": 250,
    },
    "dryad": {
        "name": "Dryad",
        "hp": 20,
        "hpmax": 20,
        "atk": 7,
        "def": 10,
        "eva": 0.6,
        "pre": 0.9,
        "c_coef": 1.7,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 50,
        "items": {"none": None},
        "dc_items": [1],
        "exp": 6,
    },
    "giant blind spider": {
        "name": "Giant Blind Spider",
        "hp": 70,
        "hpmax": 70,
        "atk": 10,
        "def": 5,
        "eva": 0.6,
        "pre": 0.8,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 5,
        "items": {"giant_silk": 1, "none": None},
        "dc_items": [0.5, 1],
        "exp": 10
    },
    "giant slime": {
        "name": "Giant Slime",
        "hp": 40,
        "hpmax": 40,
        "atk": 3,
        "def": 0,
        "eva": 0,
        "pre": 0.65,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 50,
        "items": {"slime_balls": 2, "red_potion": 1, "none": None},
        "dc_items": [0.5, 0.7, 1],
        "exp": 3
    },
    "giant spider": {
        "name": "Giant Spider",
        "hp": 70,
        "hpmax": 70,
        "atk": 10,
        "def": 5,
        "eva": 0.3,
        "pre": 0.65,
        "c_coef": 1.6,
        "c_chance": 15,
        "poison": 0,
        "c_poison": 0,
        "esc": 30,
        "items": {"giant_silk": 1, "red_potion": 1, "none": None},
        "dc_items": [0.6, 0.8, 1],
        "exp": 8
    },
    "goblin": {
        "name": "Goblin",
        "hp": 15,
        "hpmax": 15,
        "atk": 3,
        "def": 1,
        "eva": 0.3,
        "pre": 0.7,
        "c_coef": 1.5,
        "c_chance": 30,
        "poison": 0,
        "c_poison": 0,
        "esc": 45,
        "items": {"gold": 5, "red_potion": 1, "none": None},
        "dc_items": [0.5, 0.55, 1],
        "exp": 3
    },
    "goblin chief": {
        "name": "Goblin Chief",
        "hp": 75,
        "hpmax": 75,
        "atk": 5,
        "def": 3,
        "eva": 0.4,
        "pre": 0.6,
        "c_coef": 1.3,
        "c_chance": 30,
        "poison": 0,
        "c_poison": 0,
        "esc": 0,
        "items": {"gold": 60, "red_potion": 5, "none": None},
        "dc_items": [0.5, 0.95, 1],
        "exp": 30
    },
    "goblin hunter": {
        "name": "Goblin Hunter",
        "hp": 35,
        "hpmax": 35,
        "atk": 4,
        "def": 2,
        "eva": 0.5,
        "pre": 0.7,
        "c_coef": 1.5,
        "c_chance": 60,
        "poison": 2,
        "c_poison": 40,
        "esc": 50,
        "items": {"gold": 10, "bone_sword": 1, "bone_shiel": 1, "none": None},
        "dc_items": [0.5, 0.6, 0.7, 1],
        "exp": 4
    },
    "goblin war chief": {
        "name": "Goblin War Chief",
        "hp": 60,
        "hpmax": 60,
        "atk": 7,
        "def": 4,
        "eva": 0.5,
        "pre": 0.7,
        "c_coef": 1.5,
        "c_chance": 30,
        "poison": 0,
        "c_poison": 0,
        "esc": 35,
        "items": {"gold": 30, "red_potion": 1, "iron_shield": 1, "axe": 1, "none": None},
        "dc_items": [0.8, 0.85, 0.90, 0.95, 1],
        "exp": 8
    },
    "goblin war": {
        "name": "War Goblin",
        "hp": 35,
        "hpmax": 35,
        "atk": 4,
        "def": 3,
        "eva": 0.4,
        "pre": 0.7,
        "c_coef": 1.7,
        "c_chance": 40,
        "poison": 0,
        "c_poison": 0,
        "esc": 40,
        "items": {"gold": 10, "bone_sword": 1, "bone_shiel": 1, "none": None},
        "dc_items": [0.5, 0.6, 0.7, 1],
        "exp": 4
    },
    "litle slime": {
        "name": "Litle Slime",
        "hp": 10,
        "hpmax": 10,
        "atk": 2,
        "def": 0,
        "eva": 0,
        "pre": 0.8,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 60,
        "items": {"slime_balls": 1, "litle_red_potion": 1, "none": None},
        "dc_items": [0.3, 0.45, 1],
        "exp": 1
    },
    "orc": {
        "name": "Orc",
        "hp": 35,
        "hpmax": 35,
        "atk": 6,
        "def": 5,
        "eva": 0.3,
        "pre": 0.7,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 0,
        "items": {"gold": 20, "red_potion": 1, "none": None},
        "dc_items": [0.5, 0.7, 1],
        "exp": 5,
    },
    "poisonous slime": {
        "name": "Poisonous Slime",
        "hp": 20,
        "hpmax": 20,
        "atk": 3,
        "def": 1,
        "eva": 0,
        "pre": 0.7,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 1,
        "c_poison": 0.5,
        "esc": 50,
        "items": {"red_potion": 1, "slime_balls": 2, "none": None},
        "dc_items": [0.25, 0.45, 1],
        "exp": 2
    },
    "slime": {
        "name": "Slime",
        "hp": 20,
        "hpmax": 20,
        "atk": 3,
        "def": 1,
        "eva": 0,
        "pre": 0.7,
        "c_coef": 1.5,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 50,
        "items": {"red_potion": 1, "slime_balls": 2, "none": None},
        "dc_items": [0.25, 0.45, 1],
        "exp": 2
    },
    "spectral foxshade": {
        "name": "Spectral Foxshade",
        "hp": 1,
        "hpmax": 1,
        "atk": 10,
        "def": 0,
        "eva": 0,
        "pre": 1,
        "c_coef": 1.7,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 100,
        "items": {"gold": 50, "none": None},
        "dc_items": [0.9, 1],
        "exp": 15
    },
    "spectrum": {
        "name": "Spectrum",
        "hp": 40,
        "hpmax": 40,
        "atk": 10,
        "def": 0,
        "eva": 0.8,
        "pre": 0.8,
        "c_coef": 1.7,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 20,
        "items": {"none": None},
        "dc_items": [1],
        "exp": 12
    },
    "troll": {
        "name": "Troll",
        "hp": 50,
        "hpmax": 50,
        "atk": 7,
        "def": 4,
        "eva": 0.2,
        "pre": 0.75,
        "c_coef": 1.6,
        "c_chance": 20,
        "poison": 0,
        "c_poison": 0,
        "esc": 50,
        "items": {"gold": 15, "red_potion": 1, "bludgeon": 1, "none": None},
        "dc_items": [0.5, 0.6, 0.65, 1],
        "exp": 6
    },
    "watchful goblin": {
        "name": "Watchful Goblin",
        "hp": 25,
        "hpmax": 25,
        "atk": 3,
        "def": 1,
        "eva": 0.4,
        "pre": 0.7,
        "c_coef": 1.5,
        "c_chance": 30,
        "poison": 0,
        "c_poison": 0,
        "esc": 40,
        "items": {"gold": 5, "bones": 1, "none": None},
        "dc_items": [0.5, 0.55, 1],
        "exp": 3
    }
}

# NPCs.

NPCS = {
    "whispers": Npc(name="whispers",
                    npc_type=NpcTypes.WHISPERS,
                    messages={0: ["Elina...", "Elina...", "...your destiny awaits.", "Follow the whispers of the wind,"
                                                                                     " and come to me.",
                                  "Secrets untold and challenges unknown lie ahead.",
                                  "Trust in the unseen path...", "... come to me."]}),

    "captain thorne": Npc(name="captain thorne",
                          npc_type=NpcTypes.CAPTAIN,
                          messages={
                              0: ["Ahoy, traveler. I'm Captain Thorne.",
                                  "You see my ship there? We won't be setting sail today. A dragon's presence spells "
                                  "danger on the open seas. Until the skies are clear, we remain anchored. Better "
                                  "to be safe in port than to risk the wrath of such a fearsome creature.",
                                  "But fear not, when the danger has passed, I'll gladly offer you passage to the "
                                  "next port."]}),

    "captain zelian": Npc(name="captain zelian",
                          npc_type=NpcTypes.CAPTAIN,
                          messages={
                              0: ["Ah, the sea, a fickle friend and fierce foe.",
                                  "Many a ship I've sailed, battling monsters and discovering uncharted isles. "
                                  "The ocean whispers secrets to those who listen.",
                                  "One day, perhaps, the tides will reveal its mysteries to a brave soul like "
                                  "yourself, adventurer."]}),

    "dragon firefrost": Npc(name="dragon firefrost",
                            npc_type=NpcTypes.DRAGON,
                            messages={
                                0: ["Elina...",
                                    "You finally come to me...",
                                    "Destiny calls for a dance of fire and frost between us...",
                                    "Ready your blade..."]}),

    "fisherman marlin": Npc(name="fisherman marlin",
                            npc_type=NpcTypes.FISHERMAN,
                            messages={
                                0: ["Ho there, stranger! Fancy a tale from the sea? Ah, the ocean's my life.",
                                    "You know, my brother's a guard in the city, watches over the folks there. "
                                    "Dangerous duty, but he's got a heart as sturdy as a ship's hull.",
                                    "If you ever find yourself in Antina City, look for Guard Lorian. Tell him Marlin "
                                    "from Aqiri says hello."]}),

    "goblin griznuk": Npc(name="chief goblin griznuk",
                          npc_type=NpcTypes.MONSTER,
                          messages={
                              0: ["Grraaak... hssssk!", "Zilgruk!", "Fwaahh!"]}),

    "guard lorian": Npc(name="guard lorian",
                        npc_type=NpcTypes.GUARD,
                        messages={
                            0: ["Halt, traveler! Antina City permits only those with proper credentials to pass "
                                "these gates.",
                                "State your business and present your identification, or you shall not venture beyond.",
                                "The safety of our citizens is paramount, and we cannot afford to be lax in these "
                                "trying times."]}),

    "innkeeper mirabelle": Npc(name="innkeeper mirabelle",
                               npc_type=NpcTypes.INNKEEPER,
                               messages={
                                   0: ["Step into Mirabelle's Inn, weary wanderer. Here, amidst the tranquility of "
                                       "Epiiat, find shelter from the trials of the road. With hearty meals and "
                                       "soft beds, let your worries melt away."],
                                   1: ["Interested in accommodations? Take your pick of rooms tailored to your needs."],
                                   2: ["Are you looking to purchase some nourishment? What do you want?"]},
                               answers={
                                   1: "I need to sleep",
                                   2: "Buy food"},
                               buy_items={"bread": 2, "cheese": 4, "soap": 2, "water": 1, "bier": 2, "quit": 0},
                               buy_beds={"main_room": (5, "mirabelles_main_room_key"),
                                         "small_room": (3, "mirabelles_small_room_key"),
                                         "quit": (0, "quit")}),

    "lord aric": Npc(name="lord aric",
                     npc_type=NpcTypes.LORD,
                     messages={
                         0: ["Greetings, traveler. Alas, these are troubled times for our fair city.",
                             "Just days past, a dragon's shadow darkened our skies. Fear lingers in the hearts of our "
                             "citizens. The safety of Antina is at stake, and our once-stalwart walls now seem "
                             "fragile.",
                             "May the goddesses watch over us and protect us."]}),

    "mayor thorian": Npc(name="mayor thorian",
                         npc_type=NpcTypes.MAYOR,
                         messages={
                             0: ["Welcome to Epiiat, traveler.",
                                 "Though I greet you as I would any of our own, my heart is heavy with concern. My"
                                 " daughter, Maisie, has gone missing.",
                                 "She wandered off days ago, and no trace of her remains. If your path allows it, "
                                 "please keep an eye out for her.",
                                 "The villagers and I are desperate for her safe return."]}),

    "mayors daughter maisie": Npc(name="mayor's daughter maisie",
                                  npc_type=NpcTypes.MAYORS_DAUGHTER,
                                  messages={0: ["You... you saved me! I feared I'd never escape Griznuk's clutches.",
                                                "My father, the mayor, will want to thank you properly. Please, come"
                                                " back with me to the village.",
                                                "Words cannot express my gratitude, but I hope our people can repay"
                                                " your bravery."]}),

    "merchant bryson": Npc(name="merchant bryson",
                           npc_type=NpcTypes.MERCHANT,
                           messages={
                               0: ["Ah, welcome, welcome! Peruse my wares, brave one. From enchanted potions to sturdy"
                                   " shields",
                                   "Bryson's Emporium has all you need for your journey.",
                                   "Each item tells a tale, and every purchase brings you one step closer to becoming "
                                   "a legend. Don't hesitate to ask if you seek something specific, for in this square,"
                                   " dreams and adventures await!"],
                               1: ["What do you want to buy?"],
                               2: ["What do you want to sell?"]},
                           answers={
                               1: "Buy",
                               2: "Sell"},
                           buy_items={"leather_armor": 75, "leather_boots": 60, "litle_red_potion": 5,
                                      "red_potion": 10, "short_sword": 100, "wood_shield": 50, "torch": 20,
                                      "quit": 0}),

    "merchant elden": Npc(name="merchant elden",
                          npc_type=NpcTypes.MERCHANT,
                          messages={0: ["Hail, warrior! Seek the finest blades and armor in Antina? Forge Master Elden "
                                        "crafts each piece with skill and care. From gleaming swords to resilient "
                                        "shields, my forge yields the tools to shape your destiny.",
                                        "Arm yourself, adventurer, and may the battles you face be victorious!"],
                                    1: ["What do you want to buy?"],
                                    2: ["What do you want to sell?"]},
                          answers={
                              1: "Buy",
                              2: "Sell"},
                          buy_items={"axe": 280, "chainmail_armor": 300, "large_bow": 220, "longsword": 350,
                                     "iron_shield": 130, "mesh_boots": 100, "plate_armor": 400, "spear": 250,
                                     "spike_shield": 150, "tower_shield": 150, "quit": 0}),

    "merchant roland": Npc(name="merchant roland",
                           npc_type=NpcTypes.MERCHANT,
                           messages={0: ["Greetings, noble traveler! Step into Roland's Emporium, where treasures and "
                                         "trinkets await your discerning eye. From potions to weapons, my wares are "
                                         "the finest in Antina.",
                                         "Peruse at your leisure, and may your coffers overflow with the spoils of a "
                                         "grand adventure!"],
                                     1: ["What do you want to buy?"],
                                     2: ["What do you want to sell?"]},
                           answers={
                               1: "Buy",
                               2: "Sell"},
                           buy_items={"giant_red_potion": 15, "red_potion": 10, "sword": 300, "iron_shield": 150,
                                      "torch": 20, "quit": 0}),

    "merchant selena": Npc(name="merchant selena",
                           npc_type=NpcTypes.MERCHANT,
                           messages={
                               0: ["Ahoy, brave one! Step right up and behold the treasures of Aqiri's Market!",
                                   "From the finest catches of the sea to enchanted trinkets, Selena's Wares has all "
                                   "you desire. A purchase to aid your journey, perhaps?",
                                   "Sail through our goods, and may your pouch grow lighter with satisfaction!"],
                               1: ["What do you want to buy?"],
                               2: ["What do you want to sell?"]},
                           answers={
                               1: "Buy",
                               2: "Sell"},
                           buy_items={"harpoon": 150, "hardened_leather_armor": 120, "red_potion": 10,
                                      "fishing_pole": 9999, "wood_shield": 50, "telescope": 200, "quit": 0}),

    "traveler elara": Npc(
        name="traveler elara",
        npc_type=NpcTypes.TRAVELER,
        messages={
            0: ["Greetings, seeker of paths! If you yearn to traverse the mighty mountain range that veils our"
                " land, head eastward.",
                "Beyond the emerald canopy and whispering trees lies a hidden valley. It weaves through the ancient "
                "peaks, offering passage to those who dare to journey.",
                "Take heed, for the woods conceal both mystery and peril, but the call of adventure echoes through "
                "the leaves. May the spirits guide your way, brave traveler."],
            1: ["Northward, the land ascends into highlands infested with goblins and other vile creatures. A "
                "challenge for even the most seasoned adventurer."],
            2: ["To the south, dense woodlands stretch as far as the eye can see.",
                "An enchanting realm, but one must tread cautiously, for shadows dance amidst the trees."],
            3: ["Nay, brave one. The west remains a mystery to me. My journey has yet to unveil the secrets concealed "
                "in those unexplored lands.", "Perhaps one day, the winds of fate will carry me in that direction."]},
        leave_message=["May the spirits guide your way, brave traveler."],
        answers={
            1: "What lies to the north?",
            2: "And what of the southern lands?",
            3: "What about the western reaches? Have you ventured there?"}),

    "traveler elinor": Npc(name="traveler elinor",
                           npc_type=NpcTypes.TRAVELER,
                           messages={
                               0: ["Alas, the city gates remain closed to me. But fear not, fellow wanderer!",
                                   "To the east lies the charming fishing village of Aquiri. A quaint haven where the"
                                   " sea breeze dances with the scent of salt and adventure.",
                                   "Seek refuge there, share tales with the fishermen, and who knows, perhaps your "
                                   "path will intertwine with the whims of destiny. May the winds guide your steps, "
                                   "for there is always another path to tread."]}),

    "traveler kaelin": Npc(name="traveler kaelin",
                           npc_type=NpcTypes.TRAVELER,
                           messages={
                               0: ["Hail, fellow wanderer. I've treaded the southern realms, through the treacherous "
                                   "Dark Forest.",
                                   "A word of caution, brave soul – the woods conceal more than beauty. Dark whispers "
                                   "and lurking dangers await. I'd advise against venturing there unless your courage "
                                   "knows no bounds.",
                                   "May your travels be safer than mine, and the path you choose be bathed in the "
                                   "light of wisdom."]}),

    "traveler renan": Npc(name="traveler renan",
                          npc_type=NpcTypes.TRAVELER,
                          messages={0: ["You look like you’ve seen your share of the road, friend. If you need rest, "
                                        "look for an inn—there’s no better place to regain your strength.",
                                        "A warm bed and a hearty meal can make all the difference before facing "
                                        "whatever lies ahead."]}),

    "traveler seraph": Npc(name="traveler seraph",
                           npc_type=NpcTypes.TRAVELER,
                           messages={0: ["Ah, greetings, fellow wayfarer! Stuck, just like me, eh? Gorrick here "
                                         "mentioned some caves to the north that might lead us across.",
                                         "Aye, those caves are an option, but beware! Lately, they've become a haven "
                                         "for Goblins and other foul creatures.",
                                         "A perilous journey awaits, my friend. Tread "
                                         "carefully if you choose that path."]}),

    "traveler sylas": Npc(name="traveler sylas",
                          npc_type=NpcTypes.TRAVELER,
                          messages={
                              0: ["Greetings, wanderer. A word of wisdom for your journey: always embrace exploration.",
                                  "Hidden wonders and untold tales await those who venture beyond the familiar. May "
                                  "your steps be guided by curiosity, and may the world unveil its mysteries before "
                                  "you."]}),

    "traveler thaldir": Npc(name="traveler thaldir",
                            npc_type=NpcTypes.TRAVELER,
                            messages={
                                0: ["Greetings, seeker of fortune. Remember, in every step, 'tis wise to look around "
                                    "and check. Secrets often hide where the eye does not linger.",
                                    "May the journey unveil the unseen, brave one."]}),

    "villager doran": Npc(name="villager doran",
                          npc_type=NpcTypes.VILLAGER,
                          messages={
                              0: ["Ah, nothing like a good drink and a hot meal after a long day. The bard's song"
                                  " tonight is a fine one—fills the air with tales of heroes and lost treasures.",
                                  "Sit and listen a while, friend. The road can wait a moment longer, can’t it?"]}),

    "villager fira": Npc(name="villager fira",
                         npc_type=NpcTypes.VILLAGER,
                         messages={
                             0: ["Oh, traveler, have you heard? The mayor’s daughter, Maisie, hasn’t been seen "
                                 "for days."
                                 " I’m so worried—she’s always been kind to us all.",
                                 "If she’s in danger, we must do something. Please, if you find any trace of her, "
                                 "let the mayor know."]}),

    "villager merrin": Npc(name="villager merrin",
                           npc_type=NpcTypes.VILLAGER,
                           messages={
                               0: ["Oh, traveler, have you heard? The mayor’s daughter, Elara, has gone missing.",
                                   "Some say she wandered too far, but I fear the worst... The goblins have been"
                                   " lurking near the forest caves lately. It’s possible they’ve taken her.",
                                   "I hope I’m wrong, but we need help before it’s too late."]}),

    "worker gorrick": Npc(name="worker gorrick",
                          npc_type=NpcTypes.WORKER,
                          messages={
                              0: ["Oh, traveler, have you heard? The mayor’s daughter, Elara, has gone missing.",
                                  "Some say she wandered too far, but I fear the worst... The goblins have been "
                                  "lurking near the forest caves lately. It’s possible they’ve taken her. ",
                                  "I hope I’m wrong, but we need help before it’s too late."]}),
}
